# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(190, 115)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(190, 115))
        MainWindow.setMaximumSize(QtCore.QSize(190, 115))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabsMain = QtWidgets.QTabWidget(self.centralwidget)
        self.tabsMain.setEnabled(True)
        self.tabsMain.setGeometry(QtCore.QRect(0, 0, 190, 130))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabsMain.sizePolicy().hasHeightForWidth())
        self.tabsMain.setSizePolicy(sizePolicy)
        self.tabsMain.setMinimumSize(QtCore.QSize(190, 130))
        self.tabsMain.setMaximumSize(QtCore.QSize(190, 130))
        self.tabsMain.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabsMain.setUsesScrollButtons(False)
        self.tabsMain.setObjectName("tabsMain")
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.btnStart = QtWidgets.QPushButton(self.main)
        self.btnStart.setGeometry(QtCore.QRect(10, 75, 71, 31))
        self.btnStart.setObjectName("btnStart")
        self.btnStop = QtWidgets.QPushButton(self.main)
        self.btnStop.setEnabled(False)
        self.btnStop.setGeometry(QtCore.QRect(90, 75, 71, 31))
        self.btnStop.setObjectName("btnStop")
        self.gridLayoutWidget = QtWidgets.QWidget(self.main)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 151, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbTimerTimeout = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbTimerTimeout.setStyleSheet("\n"
"font: bold 20px;")
        self.lbTimerTimeout.setObjectName("lbTimerTimeout")
        self.gridLayout.addWidget(self.lbTimerTimeout, 1, 1, 1, 1)
        self.lbTimerSession = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbTimerSession.setStyleSheet("\n"
"font: bold 20px;")
        self.lbTimerSession.setObjectName("lbTimerSession")
        self.gridLayout.addWidget(self.lbTimerSession, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet("\n"
"font: 13px bold;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setStyleSheet("\n"
"font: 13px bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tabsMain.addTab(self.main, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.btnSaveProfile = QtWidgets.QPushButton(self.settings)
        self.btnSaveProfile.setGeometry(QtCore.QRect(128, 80, 34, 27))
        self.btnSaveProfile.setObjectName("btnSaveProfile")
        self.formLayoutWidget = QtWidgets.QWidget(self.settings)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 161, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lbProfileName = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbProfileName.setObjectName("lbProfileName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbProfileName)
        self.leProfileName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.leProfileName.setObjectName("leProfileName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leProfileName)
        self.lbSessionDuration = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbSessionDuration.setObjectName("lbSessionDuration")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbSessionDuration)
        self.teSessionDuration = QtWidgets.QTimeEdit(self.formLayoutWidget)
        self.teSessionDuration.setObjectName("teSessionDuration")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.teSessionDuration)
        self.lbTimeout = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbTimeout.setObjectName("lbTimeout")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbTimeout)
        self.teTimeout = QtWidgets.QTimeEdit(self.formLayoutWidget)
        self.teTimeout.setObjectName("teTimeout")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.teTimeout)
        self.cbSavedProfiles = QtWidgets.QComboBox(self.settings)
        self.cbSavedProfiles.setGeometry(QtCore.QRect(0, 81, 121, 25))
        self.cbSavedProfiles.setObjectName("cbSavedProfiles")
        self.tabsMain.addTab(self.settings, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabsMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tomatoe"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        #self.lbTimerTimeout.setText(_translate("MainWindow", "09:00:00"))
        #self.lbTimerSession.setText(_translate("MainWindow", "09:00:00"))
        self.label_2.setText(_translate("MainWindow", "Timeout"))
        self.label.setText(_translate("MainWindow", "Session"))
        self.tabsMain.setTabText(self.tabsMain.indexOf(self.main), _translate("MainWindow", "Main"))
        self.btnSaveProfile.setText(_translate("MainWindow", "Ok"))
        self.lbProfileName.setText(_translate("MainWindow", "Name"))
        self.lbSessionDuration.setText(_translate("MainWindow", "Session"))
        self.lbTimeout.setText(_translate("MainWindow", "Timeout"))
        self.tabsMain.setTabText(self.tabsMain.indexOf(self.settings), _translate("MainWindow", "Settings"))



